"""audios table

Revision ID: 302aae337a46
Revises: 37f06a334dbf
Create Date: 2018-12-29 16:28:43.962280

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '302aae337a46'
down_revision = '37f06a334dbf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('filepath', sa.String(length=120), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audio_created'), 'audio', ['created'], unique=False)
    op.create_index(op.f('ix_audio_filepath'), 'audio', ['filepath'], unique=True)
    op.create_index(op.f('ix_audio_name'), 'audio', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_audio_name'), table_name='audio')
    op.drop_index(op.f('ix_audio_filepath'), table_name='audio')
    op.drop_index(op.f('ix_audio_created'), table_name='audio')
    op.drop_table('audio')
    # ### end Alembic commands ###
