"""added active field to programs

Revision ID: 8454257497c4
Revises: d58f5a9fcebf
Create Date: 2019-01-06 02:55:29.387256

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8454257497c4'
down_revision = 'd58f5a9fcebf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('program', sa.Column('active', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_program_active'), 'program', ['active'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_program_active'), table_name='program')
    op.drop_column('program', 'active')
    # ### end Alembic commands ###
