"""table action

Revision ID: a21748d2e473
Revises: ab5faca97ade
Create Date: 2019-02-16 00:13:28.052149

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a21748d2e473'
down_revision = 'ab5faca97ade'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('action',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_action_action'), 'action', ['action'], unique=False)
    op.create_index(op.f('ix_action_category'), 'action', ['category'], unique=False)
    op.create_table('voice_command',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('command', sa.String(length=256), nullable=True),
    sa.Column('modified', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_voice_command_command'), 'voice_command', ['command'], unique=True)
    op.create_index(op.f('ix_voice_command_modified'), 'voice_command', ['modified'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_voice_command_modified'), table_name='voice_command')
    op.drop_index(op.f('ix_voice_command_command'), table_name='voice_command')
    op.drop_table('voice_command')
    op.drop_index(op.f('ix_action_category'), table_name='action')
    op.drop_index(op.f('ix_action_action'), table_name='action')
    op.drop_table('action')
    # ### end Alembic commands ###
