"""empty message

Revision ID: a4a0a5ada317
Revises: 9689640fda5e
Create Date: 2019-08-02 12:23:29.582573

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4a0a5ada317'
down_revision = '9689640fda5e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audio_category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('modified', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audio_category_modified'), 'audio_category', ['modified'], unique=False)
    op.create_index(op.f('ix_audio_category_name'), 'audio_category', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_audio_category_name'), table_name='audio_category')
    op.drop_index(op.f('ix_audio_category_modified'), table_name='audio_category')
    op.drop_table('audio_category')
    # ### end Alembic commands ###
