"""init

Revision ID: bd89de30b43e
Revises: 
Create Date: 2019-08-02 15:42:29.715751

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd89de30b43e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('action',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_action_action'), 'action', ['action'], unique=False)
    op.create_index(op.f('ix_action_category'), 'action', ['category'], unique=False)
    op.create_table('audio_category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('modified', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audio_category_modified'), 'audio_category', ['modified'], unique=False)
    op.create_index(op.f('ix_audio_category_name'), 'audio_category', ['name'], unique=True)
    op.create_table('program',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('description', sa.String(length=228), nullable=True),
    sa.Column('filepath', sa.String(length=120), nullable=True),
    sa.Column('modified', sa.DateTime(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_program_active'), 'program', ['active'], unique=False)
    op.create_index(op.f('ix_program_description'), 'program', ['description'], unique=False)
    op.create_index(op.f('ix_program_filepath'), 'program', ['filepath'], unique=True)
    op.create_index(op.f('ix_program_modified'), 'program', ['modified'], unique=False)
    op.create_index(op.f('ix_program_name'), 'program', ['name'], unique=True)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('about_me', sa.String(length=140), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('voice_command',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('command', sa.String(length=256), nullable=True),
    sa.Column('modified', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_voice_command_command'), 'voice_command', ['command'], unique=True)
    op.create_index(op.f('ix_voice_command_modified'), 'voice_command', ['modified'], unique=False)
    op.create_table('word',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('word', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_word_word'), 'word', ['word'], unique=True)
    op.create_table('audio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('content', sa.String(length=128), nullable=True),
    sa.Column('filepath', sa.String(length=120), nullable=True),
    sa.Column('modified', sa.DateTime(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['audio_category.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audio_content'), 'audio', ['content'], unique=False)
    op.create_index(op.f('ix_audio_filepath'), 'audio', ['filepath'], unique=True)
    op.create_index(op.f('ix_audio_modified'), 'audio', ['modified'], unique=False)
    op.create_index(op.f('ix_audio_name'), 'audio', ['name'], unique=True)
    op.create_table('post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('body', sa.String(length=140), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_post_timestamp'), 'post', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_post_timestamp'), table_name='post')
    op.drop_table('post')
    op.drop_index(op.f('ix_audio_name'), table_name='audio')
    op.drop_index(op.f('ix_audio_modified'), table_name='audio')
    op.drop_index(op.f('ix_audio_filepath'), table_name='audio')
    op.drop_index(op.f('ix_audio_content'), table_name='audio')
    op.drop_table('audio')
    op.drop_index(op.f('ix_word_word'), table_name='word')
    op.drop_table('word')
    op.drop_index(op.f('ix_voice_command_modified'), table_name='voice_command')
    op.drop_index(op.f('ix_voice_command_command'), table_name='voice_command')
    op.drop_table('voice_command')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_program_name'), table_name='program')
    op.drop_index(op.f('ix_program_modified'), table_name='program')
    op.drop_index(op.f('ix_program_filepath'), table_name='program')
    op.drop_index(op.f('ix_program_description'), table_name='program')
    op.drop_index(op.f('ix_program_active'), table_name='program')
    op.drop_table('program')
    op.drop_index(op.f('ix_audio_category_name'), table_name='audio_category')
    op.drop_index(op.f('ix_audio_category_modified'), table_name='audio_category')
    op.drop_table('audio_category')
    op.drop_index(op.f('ix_action_category'), table_name='action')
    op.drop_index(op.f('ix_action_action'), table_name='action')
    op.drop_table('action')
    # ### end Alembic commands ###
