"""first

Revision ID: d58f5a9fcebf
Revises: 
Create Date: 2019-01-05 23:31:19.761038

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd58f5a9fcebf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('content', sa.String(length=128), nullable=True),
    sa.Column('filepath', sa.String(length=120), nullable=True),
    sa.Column('modified', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audio_content'), 'audio', ['content'], unique=False)
    op.create_index(op.f('ix_audio_filepath'), 'audio', ['filepath'], unique=True)
    op.create_index(op.f('ix_audio_modified'), 'audio', ['modified'], unique=False)
    op.create_index(op.f('ix_audio_name'), 'audio', ['name'], unique=True)
    op.create_table('program',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('description', sa.String(length=228), nullable=True),
    sa.Column('filepath', sa.String(length=120), nullable=True),
    sa.Column('modified', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_program_description'), 'program', ['description'], unique=False)
    op.create_index(op.f('ix_program_filepath'), 'program', ['filepath'], unique=True)
    op.create_index(op.f('ix_program_modified'), 'program', ['modified'], unique=False)
    op.create_index(op.f('ix_program_name'), 'program', ['name'], unique=True)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('about_me', sa.String(length=140), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('body', sa.String(length=140), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_post_timestamp'), 'post', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_post_timestamp'), table_name='post')
    op.drop_table('post')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_program_name'), table_name='program')
    op.drop_index(op.f('ix_program_modified'), table_name='program')
    op.drop_index(op.f('ix_program_filepath'), table_name='program')
    op.drop_index(op.f('ix_program_description'), table_name='program')
    op.drop_table('program')
    op.drop_index(op.f('ix_audio_name'), table_name='audio')
    op.drop_index(op.f('ix_audio_modified'), table_name='audio')
    op.drop_index(op.f('ix_audio_filepath'), table_name='audio')
    op.drop_index(op.f('ix_audio_content'), table_name='audio')
    op.drop_table('audio')
    # ### end Alembic commands ###
