"""audios content

Revision ID: db6cece28587
Revises: 302aae337a46
Create Date: 2018-12-29 17:10:46.913540

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db6cece28587'
down_revision = '302aae337a46'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audio', sa.Column('content', sa.String(length=128), nullable=True))
    op.create_index(op.f('ix_audio_content'), 'audio', ['content'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_audio_content'), table_name='audio')
    op.drop_column('audio', 'content')
    # ### end Alembic commands ###
