"""empty message

Revision ID: fd551a7629c6
Revises: 8454257497c4
Create Date: 2019-02-15 15:32:34.026833

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd551a7629c6'
down_revision = '8454257497c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audio', sa.Column('category', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_audio_category'), 'audio', ['category'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_audio_category'), table_name='audio')
    op.drop_column('audio', 'category')
    # ### end Alembic commands ###
